# Continuous integration
name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "moseq2_nlp/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "environment.yml"
      - "setup.cfg"
  push:
    branches:
      - main
    paths:
      - "moseq2_nlp/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
      - "environment.yml"
      - "setup.cfg"

jobs:
  # Lint with black, docstring check with pydocstyle, static type checking with mypy
  lint:
    # This job runs:
    #
    # 1. Linting with black
    #
    # 2. Docstring style checking with pydocstyle 
    # Note: This uses Google-style docstring convention
    # Ref: https://google.github.io/styleguide/pyguide.html
    #
    # 3. Static type checking with MyPy
    # Note: We check using Python 3.9 to use the newer conventions for generic types.
    #
    # For a workaround on previous versions, simply add this import:
    #   from __future__ import annotations
    #
    # See: https://mypy.readthedocs.io/en/stable/builtin_types.html#generic-types
    name: Lint
    runs-on: "ubuntu-22.04"
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Checkout moseq2-viz
      uses: actions/checkout@v3
      with:
        path: ./repos/moseq2-viz
        token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        repository: tischfieldlab/moseq2-viz

    - name: Install moseq2-viz
      run: |
        pip install -e ./repos/moseq2-viz

    - name: Install dependencies
      run: |
        pip install --editable .[dev]

    - name: Run Black
      run: |
        black --diff --check moseq2_nlp tests

    - name: Run pydocstyle
      run: |
        pydocstyle --convention=google moseq2_nlp/

    - name: Run MyPy
      run: |
        mypy --follow-imports=skip --ignore-missing-imports moseq2_nlp tests

  # Tests with pytest
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "windows-2022", "macos-11"]
        python: [3.8, 3.9]

    name: Tests (${{ matrix.os }}, Python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml', 'setup.cfg') }}

      - name: Setup Miniconda
        # https://github.com/conda-incubator/setup-miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: ${{ matrix.python }}
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          # environment-file: environment.yml
          activate-environment: moseq2-nlp

      - name: Checkout moseq2-viz
        uses: actions/checkout@v3
        with:
          path: ./repos/moseq2-viz
          token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
          repository: tischfieldlab/moseq2-viz

      - name: Install moseq2-viz
        run: |
          python -m pip install "numpy >=1.18.5, <=1.21"
          python -m pip install -e ./repos/moseq2-viz

      - name: Install dependencies
        run: |
          python -m pip install --editable .[dev]

      - name: Print environment info
        if: always()
        run: |
          which python
          pip --version
          conda info
          conda list

      - name: Test with pytest
        if: ${{ !(startsWith(matrix.os, 'ubuntu') && matrix.python == 3.9) }}
        run: |
          pytest

      - name: Test with pytest (with coverage)
        if: ${{ startsWith(matrix.os, 'ubuntu') && matrix.python == 3.9 }}
        run: |
          pytest --cov=moseq2_nlp --cov-report=xml tests/

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.0
        if: ${{ startsWith(matrix.os, 'ubuntu') && matrix.python == 3.9 }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: false
